baseURL = "/blip"
title = "Blip Docs"
theme = "hugo-geekdoc"
languageCode = 'en-us'

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
  [markup.goldmark.parser.attribute]
    block = true

[taxonomies]
   tag = "tags"
